### ISSUE TITLE
Logging in using JWT 

### ISSUE THREAD

**Issue by KarimFikani** [ciscospark/spark-android-sdk#7]
I'm integrating Cisco Spark into my Android app and it seems that oauth2 path requires me to pass in a webview which will mess up the user experience. Instead I want to use JWT as a way to login. The issue with that is that there is barely any documentation about what goes in the payload of a JWT.

I've been trying the following but no luck:

```
{
  "expiresIn": "<time>",
  "token": "<token>"
}
```

I'm assuming that my token is the one that I get from here (https://developer.ciscospark.com/getting-started.html) when I login and the expiration is 2 years if I don't logout. Also looked at the android sdk code and saw the following struct for a JwtToken which I'm following:

```
private class JwtToken {

        @SerializedName("expiresIn")
        long expiresIn;

        @SerializedName("token")
        String accessToken;
        
        etc...
}
```

When I paste JWT into the "App ID" edit text box I get the following response:

```
retrofitBack = --> POST https://api.ciscospark.com/v1/jwt/login http/1.1
retrofitBack = Content-Length: 0
retrofitBack = Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzSW4iOiI2MzExMzkwNCIsInRva2VuIjoiT1dGall6azNPR0l0TlROaE9TMDBaVE5tTFdGa056a3ROVEE0WTJFeFptVmxNek15WXpnMU56VTBNelF0TWpVMyJ9.DNZYRHi9ZkLfLW2_4xeAJ2moFsaHMkezAOvZi2OjYM4
retrofitBack = User-Agent: spark_android_sdk/0.2.0(2017_12_01_10_54_06_7ab2192) (Android 6.0.1; Asus Flo / Google Nexus 7;)
retrofitBack = Spark-User-Agent: spark_android_sdk/0.2.0(2017_12_01_10_54_06_7ab2192) (Android 6.0.1; Asus Flo / Google Nexus 7;)
retrofitBack = 
retrofitBack = 
retrofitBack = --> END POST (0-byte body)
retrofitBack = <-- 401  https://api.ciscospark.com/v1/jwt/login (859ms)
retrofitBack = date: Thu, 28 Dec 2017 00:11:12 GMT
retrofitBack = content-type: application/json
retrofitBack = trackingid: ROUTER_5A44369F-1A9B-01BB-5164-AC12DAEA5164
retrofitBack = cisco-spark-error-codes: 0
retrofitBack = server: Redacted
retrofitBack = l5d-success-class: 1.0
retrofitBack = via: 1.1 linkerd
retrofitBack = strict-transport-security: max-age=63072000; includeSubDomains; preload
retrofitBack = 
retrofitBack = {"errorCode":0,"message":"Unknown application","errors":[{"errorCode":0,"description":"Unknown application"}],"trackingId":"ROUTER_5A44369F-1A9B-01BB-5164-AC12DAEA5164"}
retrofitBack = <-- END HTTP (169-byte body)

```
Is that the right way to go or am I forced with the oauth2 integration?

**Comment by olivierproffit** [comment]
@KarimFikani the Guest offer using JWT is not available yet. Please Spark me (oproffit@cisco.com) if you need early access.

**Comment by olivierproffit** [comment]
@KarimFikani, when the Guest offer will be available, Guests (using JWT) will be allowed to contact only regular paid Spark users (using OAuth). JWT user to JWT user is forbidden. Happy to discuss it furthermore over Spark.

To simplify the OAuth experience, you may try Single Sign On.
